language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  matrix:
  - DB=mysql TASK=travis:backend:test
before_script:
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar);
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
- 'export JAVA_OPTS="-Xmx1G $JAVA_OPTS"'
- git clone --branch 1.5-rc3-changed-rspec-tests https://github.com/NYULibraries/archivesspace.git
- dir_name=${PWD##*/}
- echo $dir_name
- mkdir -p archivesspace/plugins/$dir_name/backend
- cp -r backend/* archivesspace/plugins/$dir_name/backend
- echo "AppConfig[:plugins] = ['$dir_name']"  > archivesspace/common/config/config.rb
- cp build.xml archivesspace/build
notifications:
  slack: nyu-dlts:soXKrVQlFYngL6O9HvlcZFz2
script:
- archivesspace/build/run $TASK $TASK_OPTS
sudo: false
