language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  matrix:
  - DB=mysql TASK=travis:backend:test
before_script:
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar);
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
- 'export JAVA_OPTS="-Xmx1G $JAVA_OPTS"'
- mkdir -p opt
- cd opt
- git clone --branch 1.5-rc3-changed-rspec-tests https://github.com/NYULibraries/archivesspace.git
- mkdir -p archivesspace/plugins/nyu_sso_plugin/backend
- cp -r ../backend/* archivesspace/plugins/nyu_sso_plugin/backend
- mkdir -p archivesspace/plugins/nyu_sso_plugin/frontend
- cp -r ../frontend/* archivesspace/plugins/nyu_sso_plugin/frontend
- cp ../Gemfile archivesspace/plugins/nyu_sso_plugin/
- echo "AppConfig[:plugins] = ['nyu_sso_plugins']"  > archivesspace/common/config/config.rb
- git clone --branch master https://github.com/NYULibraries/omniauth-nyulibraries.git
- mkdir -p archivesspace/plugins/nyu_sso_plugin/gems/gems
- cp -r omniauth-nyulibraries archivesspace/plugins/nyu_sso_plugin/gems/gems/
- gem build archivesspace/plugins/nyu_sso_plugin/gems/gems/omniauth-nyulibraries/omniauth-nyulibraries.gemspec
- gem install archivesspace/plugins/nyu_sso_plugin/gems/gems/omniauth-nyulibraries/omniauth-nyulibraries.gem
- cp ../build.xml archivesspace/build
notifications:
  slack: nyu-dlts:soXKrVQlFYngL6O9HvlcZFz2
script:
- archivesspace/build/run $TASK $TASK_OPTS
sudo: false
